# Generated by Django 2.2 on 2024-09-15 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefielditem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileFieldItem',
            new_name='ProfileFeedItem',
        ),
    ]
